/**
 * AUTOMOD PARSER VALIDATION TESTS
 *
 * This test suite validates YAML syntax against Reddit's AutoModerator specification.
 * Tests ensure generated YAML is compatible with Reddit's AutoModerator parser.
 *
 * Reference: https://www.reddit.com/wiki/automoderator
 */

import { describe, it, expect } from 'vitest';
import {
  serializeAutomodRule,
  parseAutomodRuleDraft,
  DEFAULT_AUTOMOD_RULE,
  type AutomodRule,
} from '../../shared/automod';

function buildRule(overrides: Partial<AutomodRule> = {}): AutomodRule {
  return {
    ...DEFAULT_AUTOMOD_RULE,
    id: 'test-rule',
    name: 'Test rule',
    action: 'remove',
    comment: 'Removed.',
    modmail: '{{permalink}}',
    conditions: [{ field: 'title', comparator: 'includes', value: 'test' }],
    ...overrides,
  };
}

describe('AutoModerator YAML Specification Compliance', () => {
  it('should generate valid YAML with proper document delimiters', () => {
    const rule = buildRule();
    const yaml = serializeAutomodRule(rule);

    // Reddit AutoModerator expects rules to be separated by ---
    expect(yaml).toMatch(/^---/);
    expect(yaml).toMatch(/---$/);
  });

  it('should include required type field', () => {
    const rule = buildRule();
    const yaml = serializeAutomodRule(rule);

    // type is required by AutoModerator
    expect(yaml).toMatch(/type:\s*submission/);
  });

  it('should include valid action field', () => {
    const validActions = ['remove', 'approve', 'report', 'spam', 'filter'];
    
    for (const action of validActions) {
      const rule = buildRule({ action: action as any });
      const yaml = serializeAutomodRule(rule);
      expect(yaml).toMatch(new RegExp(`action:\\s*${action}`));
    }
  });

  it('should format title conditions correctly', () => {
    const rule = buildRule({
      conditions: [{ field: 'title', comparator: 'includes', value: 'spam' }],
    });
    const yaml = serializeAutomodRule(rule);

    // Reddit format: title (includes): ['spam']
    expect(yaml).toMatch(/title\s*\(includes\):\s*\[.+\]/);
  });

  it('should format body conditions correctly', () => {
    const rule = buildRule({
      conditions: [{ field: 'body', comparator: 'includes', value: 'test' }],
    });
    const yaml = serializeAutomodRule(rule);

    expect(yaml).toMatch(/body\s*\(includes\):\s*\[.+\]/);
  });

  it('should format author conditions correctly', () => {
    const rule = buildRule({
      conditions: [
        { field: 'account_age', comparator: '<', value: '7' },
        { field: 'combined_karma', comparator: '<', value: '100' },
      ],
      satisfyAnyThreshold: true,
    });
    const yaml = serializeAutomodRule(rule);

    // Reddit format for author conditions
    expect(yaml).toMatch(/author:/);
    expect(yaml).toMatch(/account_age:/);
    expect(yaml).toMatch(/combined_karma:/);
    expect(yaml).toMatch(/satisfy_any_threshold:\s*true/);
  });

  it('should handle multi-line comments correctly', () => {
    const rule = buildRule({
      comment: 'This is a\nmulti-line\ncomment',
    });
    const yaml = serializeAutomodRule(rule);

    // Reddit supports multi-line comments with |
    expect(yaml).toMatch(/comment:\s*\|/);
    expect(yaml).toMatch(/This is a/);
    expect(yaml).toMatch(/multi-line/);
  });

  it('should handle multi-line modmail correctly', () => {
    const rule = buildRule({
      modmail: 'Post removed\n{{permalink}}',
    });
    const yaml = serializeAutomodRule(rule);

    expect(yaml).toMatch(/modmail:\s*\|/);
    expect(yaml).toMatch(/\{\{permalink\}\}/);
  });

  it('should escape special characters in values', () => {
    const rule = buildRule({
      conditions: [{ field: 'title', comparator: 'includes', value: 'test: value' }],
    });
    const yaml = serializeAutomodRule(rule);

    // Should be properly quoted
    expect(yaml).toMatch(/test:\s*value/);
  });

  it('should handle boolean fields correctly', () => {
    const rule = buildRule({
      commentStickied: true,
    });
    const yaml = serializeAutomodRule(rule);

    // Reddit expects lowercase true/false
    expect(yaml).toMatch(/comment_stickied:\s*true/);
  });

  it('should handle version comments without breaking parser', () => {
    const rule = buildRule({ version: '1.0.0' });
    const yaml = serializeAutomodRule(rule);

    // Version should be in a comment that Reddit ignores
    expect(yaml).toMatch(/#\s*Generated by RuleStage/);
    
    // Should still parse correctly
    const parsed = parseAutomodRuleDraft(yaml, DEFAULT_AUTOMOD_RULE);
    expect(parsed.name).toBe('Test rule');
  });
});

describe('Edge Cases That Reddit Parser Might Reject', () => {
  it('should handle empty values gracefully', () => {
    const rule = buildRule({
      conditions: [{ field: 'title', comparator: 'includes', value: '' }],
    });
    const yaml = serializeAutomodRule(rule);

    // Should still generate valid YAML
    expect(yaml).toMatch(/^---/);
    expect(yaml).toMatch(/---$/);
  });

  it('should handle very long strings', () => {
    const longString = 'a'.repeat(10000);
    const rule = buildRule({
      comment: longString,
    });
    const yaml = serializeAutomodRule(rule);

    // Should still be valid YAML
    expect(() => parseAutomodRuleDraft(yaml, DEFAULT_AUTOMOD_RULE)).not.toThrow();
  });

  it('should handle special regex characters', () => {
    const rule = buildRule({
      conditions: [{ field: 'title', comparator: 'matches', value: '[a-z]+.*\\d+' }],
    });
    const yaml = serializeAutomodRule(rule);

    // Should properly escape or quote regex
    expect(yaml).toMatch(/\[a-z\]/);
  });

  it('should handle unicode characters', () => {
    const rule = buildRule({
      conditions: [{ field: 'title', comparator: 'includes', value: '测试🎉' }],
    });
    const yaml = serializeAutomodRule(rule);

    // Should handle unicode properly
    expect(yaml).toContain('测试');
  });

  it('should handle null characters by rejecting them', () => {
    const rule = buildRule({
      comment: 'test\x00null',
    });

    // Should throw error for null characters
    expect(() => serializeAutomodRule(rule)).toThrow();
  });

  it('should handle very large rule sets', () => {
    const conditions = Array.from({ length: 50 }, (_, i) => ({
      field: 'title' as const,
      comparator: 'includes' as const,
      value: `keyword${i}`,
    }));
    
    const rule = buildRule({ conditions });
    const yaml = serializeAutomodRule(rule);

    // Should still be valid YAML
    expect(() => parseAutomodRuleDraft(yaml, DEFAULT_AUTOMOD_RULE)).not.toThrow();
  });

  it('should enforce 100KB size limit', () => {
    const largeComment = 'x'.repeat(100001);
    const rule = buildRule({ comment: largeComment });

    // Should throw error for content exceeding 100KB
    expect(() => serializeAutomodRule(rule)).toThrow('exceeds maximum size');
  });
});

describe('Round-Trip Compatibility', () => {
  it('should preserve rule name through serialize-parse cycle', () => {
    const original = buildRule({ name: 'Test Rule Name' });
    const yaml = serializeAutomodRule(original);
    const parsed = parseAutomodRuleDraft(yaml, DEFAULT_AUTOMOD_RULE);

    expect(parsed.name).toBe(original.name);
  });

  it('should preserve action through serialize-parse cycle', () => {
    const original = buildRule({ action: 'approve' });
    const yaml = serializeAutomodRule(original);
    const parsed = parseAutomodRuleDraft(yaml, DEFAULT_AUTOMOD_RULE);

    expect(parsed.action).toBe(original.action);
  });

  it('should preserve conditions through serialize-parse cycle', () => {
    const original = buildRule({
      conditions: [
        { field: 'title', comparator: 'includes', value: 'spam' },
        { field: 'body', comparator: 'includes', value: 'scam' },
      ],
    });
    const yaml = serializeAutomodRule(original);
    const parsed = parseAutomodRuleDraft(yaml, DEFAULT_AUTOMOD_RULE);

    expect(parsed.conditions).toHaveLength(original.conditions.length);
    expect(parsed.conditions[0].field).toBe(original.conditions[0].field);
    expect(parsed.conditions[0].value).toBe(original.conditions[0].value);
  });

  it('should preserve satisfyAnyThreshold through serialize-parse cycle', () => {
    const original = buildRule({ satisfyAnyThreshold: true });
    const yaml = serializeAutomodRule(original);
    const parsed = parseAutomodRuleDraft(yaml, DEFAULT_AUTOMOD_RULE);

    expect(parsed.satisfyAnyThreshold).toBe(original.satisfyAnyThreshold);
  });

  it('should preserve comment through serialize-parse cycle', () => {
    const original = buildRule({ comment: 'Test comment\nwith newlines' });
    const yaml = serializeAutomodRule(original);
    const parsed = parseAutomodRuleDraft(yaml, DEFAULT_AUTOMOD_RULE);

    expect(parsed.comment.trim()).toBe(original.comment);
  });

  it('should preserve modmail through serialize-parse cycle', () => {
    const original = buildRule({ modmail: '{{permalink}}' });
    const yaml = serializeAutomodRule(original);
    const parsed = parseAutomodRuleDraft(yaml, DEFAULT_AUTOMOD_RULE);

    expect(parsed.modmail).toBe(original.modmail);
  });

  it('should preserve version through serialize-parse cycle', () => {
    const original = buildRule({ version: '1.2.3' });
    const yaml = serializeAutomodRule(original);
    const parsed = parseAutomodRuleDraft(yaml, DEFAULT_AUTOMOD_RULE);

    expect(parsed.version).toBe(original.version);
  });
});

describe('Reddit-Specific Syntax Validation', () => {
  it('should use correct comparator syntax', () => {
    const comparators = ['includes', 'matches', '<', '>', '<=', '>='];
    
    for (const comparator of comparators) {
      const rule = buildRule({
        conditions: [{ field: 'title', comparator: comparator as any, value: 'test' }],
      });
      const yaml = serializeAutomodRule(rule);
      
      // Should generate valid YAML
      expect(() => parseAutomodRuleDraft(yaml, DEFAULT_AUTOMOD_RULE)).not.toThrow();
    }
  });

  it('should format list values correctly', () => {
    const rule = buildRule({
      conditions: [{ field: 'title', comparator: 'includes', value: 'spam' }],
    });
    const yaml = serializeAutomodRule(rule);

    // Reddit expects array syntax for includes/matches
    expect(yaml).toMatch(/\[.+\]/);
  });

  it('should format threshold values correctly', () => {
    const rule = buildRule({
      conditions: [
        { field: 'account_age', comparator: '<', value: '7' },
        { field: 'combined_karma', comparator: '>', value: '100' },
      ],
    });
    const yaml = serializeAutomodRule(rule);

    // Threshold values should be strings in Reddit's format
    expect(yaml).toMatch(/account_age:\s*"<\s*7"/);
    expect(yaml).toMatch(/combined_karma:\s*">\s*100"/);
  });

  it('should handle comment_stickied field', () => {
    const rule = buildRule({ commentStickied: true });
    const yaml = serializeAutomodRule(rule);

    expect(yaml).toMatch(/comment_stickied:\s*true/);
  });

  it('should handle all three action types', () => {
    const actions: Array<'remove' | 'approve' | 'report'> = ['remove', 'approve', 'report'];
    
    for (const action of actions) {
      const rule = buildRule({ action });
      const yaml = serializeAutomodRule(rule);
      const parsed = parseAutomodRuleDraft(yaml, DEFAULT_AUTOMOD_RULE);
      
      expect(parsed.action).toBe(action);
    }
  });
});

describe('Multiple Rules in Single YAML', () => {
  it('should handle multiple rules separated by ---', () => {
    const rule1 = buildRule({ name: 'Rule 1' });
    const rule2 = buildRule({ name: 'Rule 2' });
    
    const yaml1 = serializeAutomodRule(rule1);
    const yaml2 = serializeAutomodRule(rule2);
    
    const combinedYaml = yaml1 + '\n\n' + yaml2;

    // Should be able to parse both rules
    expect(combinedYaml).toMatch(/---\s*# Rule 1/);
    expect(combinedYaml).toMatch(/---\s*# Rule 2/);
  });

  it('should not create invalid YAML when merging rules', () => {
    const rule1 = buildRule({ name: 'Rule 1' });
    const rule2 = buildRule({ name: 'Rule 2' });
    
    const yaml1 = serializeAutomodRule(rule1);
    const yaml2 = serializeAutomodRule(rule2);
    
    const combinedYaml = yaml1 + '\n\n' + yaml2;

    // Combined YAML should still be valid
    expect(combinedYaml).toMatch(/^---/);
    expect(combinedYaml).toMatch(/---$/);
  });
});
