import { describe, it, expect, vi, beforeEach } from 'vitest';

// --- Mock @devvit/web/server before importing service ---
const { mockRedisGet, mockRedisSet, mockRedisDel, mockUpdateWikiPage, mockGetWikiPage } = vi.hoisted(() => ({
  mockRedisGet: vi.fn(),
  mockRedisSet: vi.fn(),
  mockRedisDel: vi.fn(),
  mockUpdateWikiPage: vi.fn(),
  mockGetWikiPage: vi.fn(),
}));

vi.mock('@devvit/web/server', () => ({
  redis: {
    get: mockRedisGet,
    set: mockRedisSet,
    del: mockRedisDel,
  },
  reddit: {
    updateWikiPage: mockUpdateWikiPage,
    getWikiPage: mockGetWikiPage,
  },
  context: {
    get subredditName() { return currentSubreddit; },
  },
}));

// Track which subreddit context is active
let currentSubreddit = 'testsub';

// Import after mock is registered
import {
  saveCurrentRule,
  getCurrentRule,
  pushYamlToWiki,
} from '../../server/services/automod.service';
import {
  DEFAULT_AUTOMOD_RULE,
  serializeAutomodRule,
  type AutomodRule,
} from '../../shared/automod';

function buildRule(overrides: Partial<AutomodRule> = {}): AutomodRule {
  return {
    ...DEFAULT_AUTOMOD_RULE,
    id: 'test-rule',
    name: 'Spam guard',
    action: 'remove',
    comment: 'Removed.',
    modmail: '{{permalink}}',
    conditions: [{ field: 'title', comparator: 'includes', value: 'spam' }],
    ...overrides,
  };
}

beforeEach(() => {
  vi.clearAllMocks();
  currentSubreddit = 'testsub';
  mockRedisGet.mockResolvedValue(null);
  mockRedisSet.mockResolvedValue(null);
  mockRedisDel.mockResolvedValue(null);
  mockUpdateWikiPage.mockResolvedValue(undefined);
  mockGetWikiPage.mockResolvedValue(null);
});

// ─── Full E2E Workflow Tests ─────────────────────────────────────────────────

describe('Full E2E Workflow - Chat → YAML → Wiki → Live', () => {
  it('should complete full workflow: save rule to Redis, serialize to YAML, push to wiki', async () => {
    // Step 1: Create a rule (simulating chat/code generation)
    const rule = buildRule({
      name: 'Crypto spam filter',
      version: '1.0.0',
      conditions: [{ field: 'title', comparator: 'includes', value: 'crypto' }],
    });

    // Step 2: Save rule to Redis (simulating draft save)
    await saveCurrentRule(rule);

    // Verify rule was saved to Redis
    expect(mockRedisSet).toHaveBeenCalledOnce();
    const redisCall = mockRedisSet.mock.calls[0];
    expect(redisCall[0]).toContain('rulestage:rule:current');
    expect(redisCall[1]).toContain('Crypto spam filter');

    // Step 3: Verify YAML serialization (simulating YAML generation)
    const yaml = serializeAutomodRule(rule);
    expect(yaml).toContain('# Crypto spam filter');
    expect(yaml).toContain('# Generated by RuleStage v1.0.0');
    expect(yaml).toContain('title (includes): [\'crypto\']');
    expect(yaml).toContain('action: remove');

    // Step 4: Push to wiki (simulating deployment)
    mockGetWikiPage.mockResolvedValue({ content_md: '' });
    mockUpdateWikiPage.mockClear(); // Clear mock from saveCurrentRule call
    await pushYamlToWiki(yaml);

    // Verify wiki was updated
    expect(mockUpdateWikiPage).toHaveBeenCalledOnce();
    const wikiCall = mockUpdateWikiPage.mock.calls[0][0] as { content: string };
    expect(wikiCall.content).toContain('Crypto spam filter');
    expect(wikiCall.content).toContain('Generated by RuleStage v1.0.0');
  });

  it('should preserve existing wiki rules during deployment', async () => {
    // Step 1: Simulate existing wiki content
    const existingWikiContent = `---
# Old spam filter
type: submission
action: remove
comment: Old spam
modmail: Old
---`;

    mockGetWikiPage.mockResolvedValue({ content_md: existingWikiContent });

    // Step 2: Create and save new rule
    const newRule = buildRule({
      name: 'New crypto filter',
      version: '1.0.0',
      conditions: [{ field: 'title', comparator: 'includes', value: 'crypto' }],
    });

    await saveCurrentRule(newRule);

    // Step 3: Push to wiki (should merge)
    const newYaml = serializeAutomodRule(newRule);
    await pushYamlToWiki(newYaml);

    // Step 4: Verify both rules are in wiki
    const wikiCall = mockUpdateWikiPage.mock.calls[0][0] as { content: string };
    expect(wikiCall.content).toContain('Old spam filter');
    expect(wikiCall.content).toContain('New crypto filter');

    // Step 5: Deploy the same rule again to test idempotency
    mockGetWikiPage.mockResolvedValue({ content_md: wikiCall.content });
    mockUpdateWikiPage.mockClear();
    await saveCurrentRule(newRule);

    // Step 6: Verify each rule name appears exactly once (no duplication)
    const secondWikiCall = mockUpdateWikiPage.mock.calls[0][0] as { content: string };
    const oldMatches = (secondWikiCall.content.match(/# Old spam filter/g) ?? []).length;
    const newMatches = (secondWikiCall.content.match(/# New crypto filter/g) ?? []).length;
    expect(oldMatches).toBe(1);
    expect(newMatches).toBe(1);
  });

  it('should handle empty wiki on first deployment', async () => {
    // Step 1: Wiki doesn't exist yet
    mockGetWikiPage.mockRejectedValue(new Error('wiki not found'));

    // Step 2: Create and save first rule
    const rule = buildRule({
      name: 'First rule',
      version: '1.0.0',
    });

    await saveCurrentRule(rule);

    // Step 3: Push to wiki
    const yaml = serializeAutomodRule(rule);
    await pushYamlToWiki(yaml);

    // Step 4: Verify wiki was created with just the new rule
    const wikiCall = mockUpdateWikiPage.mock.calls[0][0] as { content: string };
    expect(wikiCall.content).toContain('First rule');
    expect(wikiCall.content).toContain('Generated by RuleStage v1.0.0');
  });

  it('should retrieve draft from Redis and continue workflow', async () => {
    // Step 1: Save initial draft
    const initialRule = buildRule({ name: 'Draft rule' });
    await saveCurrentRule(initialRule);

    // Step 2: Retrieve draft (simulating user returning to edit)
    mockRedisGet.mockResolvedValue(serializeAutomodRule(initialRule));
    const retrieved = await getCurrentRule();

    expect(retrieved.name).toBe('Draft rule');

    // Step 3: Modify and save
    const modifiedRule = { ...retrieved, name: 'Modified rule', version: '1.0.0' };
    await saveCurrentRule(modifiedRule);

    // Step 4: Push to wiki
    mockGetWikiPage.mockResolvedValue({ content_md: '' });
    const yaml = serializeAutomodRule(modifiedRule);
    await pushYamlToWiki(yaml);

    // Step 5: Verify final state (get the last call since saveCurrentRule also calls pushYamlToWiki)
    const wikiCall = mockUpdateWikiPage.mock.calls[mockUpdateWikiPage.mock.calls.length - 1][0] as { content: string };
    expect(wikiCall.content).toContain('Modified rule');
  });
});

// ─── Version Tracking in E2E Workflow ─────────────────────────────────────────

describe('E2E Workflow - Version Tracking', () => {
  it('should include version in deployed YAML', async () => {
    const rule = buildRule({ name: 'Versioned rule', version: '2.1.0' });
    await saveCurrentRule(rule);

    mockGetWikiPage.mockResolvedValue({ content_md: '' });
    const yaml = serializeAutomodRule(rule);
    await pushYamlToWiki(yaml);

    const wikiCall = mockUpdateWikiPage.mock.calls[0][0] as { content: string };
    expect(wikiCall.content).toContain('# Generated by RuleStage v2.1.0');
  });

  it('should handle rules without version (legacy compatibility)', async () => {
    const rule = buildRule({ name: 'Legacy rule' }); // No version
    await saveCurrentRule(rule);

    mockGetWikiPage.mockResolvedValue({ content_md: '' });
    const yaml = serializeAutomodRule(rule);
    await pushYamlToWiki(yaml);

    const wikiCall = mockUpdateWikiPage.mock.calls[0][0] as { content: string };
    expect(wikiCall.content).toContain('Legacy rule');
    expect(wikiCall.content).not.toContain('Generated by RuleStage');
  });
});

// ─── Error Handling in E2E Workflow ───────────────────────────────────────────

describe('E2E Workflow - Error Handling', () => {
  it('should handle subreddit context errors gracefully', async () => {
    currentSubreddit = 'default'; // Invalid context

    const rule = buildRule({ name: 'Test rule' });

    // Should throw when trying to push to wiki without valid context
    await expect(pushYamlToWiki(serializeAutomodRule(rule))).rejects.toThrow(
      'No subreddit context available'
    );
  });

  it('should handle wiki read errors during merge', async () => {
    // Wiki read fails
    mockGetWikiPage.mockRejectedValue(new Error('Wiki API error'));

    const rule = buildRule({ name: 'Test rule', version: '1.0.0' });
    await saveCurrentRule(rule);

    // Clear mocks to isolate the pushYamlToWiki call
    mockUpdateWikiPage.mockClear();

    // Should still push (treat as empty wiki)
    const yaml = serializeAutomodRule(rule);
    await pushYamlToWiki(yaml);

    expect(mockUpdateWikiPage).toHaveBeenCalledOnce();
    const wikiCall = mockUpdateWikiPage.mock.calls[0][0] as { content: string };
    expect(wikiCall.content).toContain('Test rule');
  });
});
