// src/server/__tests__/version-stamping.test.ts

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ── Hoist mocks before any imports ───────────────────────────────────────────
const { mockRedisGet, mockRedisSet, mockUpdateWikiPage, mockGetWikiPage } = vi.hoisted(() => ({
  mockRedisGet: vi.fn(),
  mockRedisSet: vi.fn(),
  mockUpdateWikiPage: vi.fn(),
  mockGetWikiPage: vi.fn(),
}));

vi.mock('@devvit/web/server', () => ({
  redis: { get: mockRedisGet, set: mockRedisSet, del: vi.fn() },
  reddit: { updateWikiPage: mockUpdateWikiPage, getWikiPage: mockGetWikiPage },
  context: { subredditName: 'testsub' },
}));

import { saveCurrentRule } from '../../server/services/automod.service';
import { parseAutomodRuleDraft, DEFAULT_AUTOMOD_RULE, type AutomodRule } from '../../shared/automod';
import pkg from '../../../package.json';
import devvitJson from '../../../devvit.json';

function buildRule(overrides: Partial<AutomodRule> = {}): AutomodRule {
  return {
    ...DEFAULT_AUTOMOD_RULE,
    id: 'test-rule',
    name: 'Spam guard',
    action: 'remove',
    comment: 'Removed.',
    modmail: '{{permalink}}',
    conditions: [{ field: 'title', comparator: 'includes', value: 'spam' }],
    ...overrides,
  };
}

beforeEach(() => {
  vi.clearAllMocks();
  mockRedisGet.mockResolvedValue(null);
  mockRedisSet.mockResolvedValue(null);
  mockUpdateWikiPage.mockResolvedValue(undefined);
  mockGetWikiPage.mockRejectedValue(new Error('not found'));
});

// ─── Version stamped on save ─────────────────────────────────────────────────

describe('Version stamping during saveCurrentRule', () => {
  it('stamps package.json version onto the rule before writing to wiki', async () => {
    const rule = buildRule();
    await saveCurrentRule(rule);

    const wikiContent: string = mockUpdateWikiPage.mock.calls[0][0].content;
    expect(wikiContent).toContain(`# Generated by RuleStage v${pkg.version}`);
  });

  it('stamped version in wiki content is parseable back to the same version', async () => {
    const rule = buildRule();
    await saveCurrentRule(rule);

    const wikiContent: string = mockUpdateWikiPage.mock.calls[0][0].content;
    const parsed = parseAutomodRuleDraft(wikiContent, DEFAULT_AUTOMOD_RULE);
    expect(parsed.version).toBe(pkg.version);
  });

  it('returned rule from saveCurrentRule includes version field', async () => {
    const rule = buildRule();
    const saved = await saveCurrentRule(rule);
    expect(saved.version).toBe(pkg.version);
  });

  it('version survives Redis round-trip (stored yaml also has version)', async () => {
    const rule = buildRule();
    await saveCurrentRule(rule);

    const storedYaml: string = mockRedisSet.mock.calls[0][1];
    expect(storedYaml).toContain(`Generated by RuleStage v${pkg.version}`);
  });
});

// ─── package.json ↔ devvit.json consistency ──────────────────────────────────

describe('package.json and devvit.json version consistency', () => {
  it('devvit.json exists and has a version field', () => {
    // devvit.json currently lacks a version — this test will fail and flag that
    expect(typeof (devvitJson as any).version).toBe('string');
  });

  it('devvit.json version matches package.json version', () => {
    expect((devvitJson as any).version).toBe(pkg.version);
  });

  it('package.json version is a valid semver string', () => {
    expect(pkg.version).toMatch(/^\d+\.\d+\.\d+/);
  });
});
