import { describe, it, expect } from 'vitest';
import {
  DEFAULT_AUTOMOD_RULE,
  serializeAutomodRule,
  parseAutomodRuleDraft,
  type AutomodRule,
} from '../../shared/automod';

function buildRule(overrides: Partial<AutomodRule> = {}): AutomodRule {
  return {
    ...DEFAULT_AUTOMOD_RULE,
    id: 'test-rule',
    name: 'Spam guard',
    action: 'remove',
    comment: 'Removed.',
    modmail: '{{permalink}}',
    conditions: [{ field: 'title', comparator: 'includes', value: 'spam' }],
    ...overrides,
  };
}

// ─── Version Serialization Tests ─────────────────────────────────────────────

describe('Version Serialization', () => {
  it('should include version in YAML when version is set', () => {
    const rule = buildRule({ version: '1.0.0' });
    const yaml = serializeAutomodRule(rule);

    expect(yaml).toContain('# Generated by RuleStage v1.0.0');
  });

  it('should not include version comment when version is not set', () => {
    const rule = buildRule({});
    const yaml = serializeAutomodRule(rule);

    expect(yaml).not.toContain('Generated by RuleStage');
  });

  it('should include version comment after rule name', () => {
    const rule = buildRule({ name: 'Test Rule', version: '2.1.0' });
    const yaml = serializeAutomodRule(rule);

    const lines = yaml.split('\n');
    const nameIndex = lines.findIndex((line) => line.includes('# Test Rule'));
    const versionIndex = lines.findIndex((line) => line.includes('Generated by RuleStage'));

    expect(nameIndex).toBeGreaterThan(-1);
    expect(versionIndex).toBeGreaterThan(nameIndex);
  });

  it('should handle semantic versioning format', () => {
    const rule = buildRule({ version: '1.2.3-beta.1' });
    const yaml = serializeAutomodRule(rule);

    expect(yaml).toContain('# Generated by RuleStage v1.2.3-beta.1');
  });
});

// ─── Version Parsing Tests ───────────────────────────────────────────────────

describe('Version Parsing', () => {
  it('should parse rule without version comment', () => {
    const yaml = `---
# Spam guard
type: submission
title (includes): ['spam']
author:
  satisfy_any_threshold: true
action: remove
comment_stickied: false
comment: |
  Removed.
modmail: |
  {{permalink}}
---`;

    const parsed = parseAutomodRuleDraft(yaml);
    expect(parsed.name).toBe('Spam guard');
    expect(parsed.version).toBeUndefined();
  });

  it('should parse rule with version comment', () => {
    const yaml = `---
# Spam guard
# Generated by RuleStage v1.0.0
type: submission
title (includes): ['spam']
author:
  satisfy_any_threshold: true
action: remove
comment_stickied: false
comment: |
  Removed.
modmail: |
  {{permalink}}
---`;

    const parsed = parseAutomodRuleDraft(yaml);
    expect(parsed.name).toBe('Spam guard');
    expect(parsed.version).toBe('1.0.0');
  });
});

// ─── Version Compatibility Tests ────────────────────────────────────────────

describe('Version Compatibility', () => {
  it('should detect version from YAML comment', () => {
    const yaml = `---
# Test Rule
# Generated by RuleStage v1.0.0
type: submission
title (includes): ['test']
author:
  satisfy_any_threshold: true
action: remove
comment_stickied: false
---`;

    const versionMatch = yaml.match(/Generated by RuleStage v(\d+\.\d+\.\d+)/);
    expect(versionMatch).toBeTruthy();
    expect(versionMatch?.[1]).toBe('1.0.0');
  });

  it('should handle rules without version (legacy)', () => {
    const yaml = `---
# Legacy Rule
type: submission
title (includes): ['legacy']
author:
  satisfy_any_threshold: true
action: remove
comment_stickied: false
---`;

    const versionMatch = yaml.match(/Generated by RuleStage v(\d+\.\d+\.\d+)/);
    expect(versionMatch).toBeNull();
  });

  it('should compare versions for compatibility', () => {
    const currentVersion = '1.0.0';
    const ruleVersion = '1.0.0';

    const isCompatible = currentVersion === ruleVersion;
    expect(isCompatible).toBe(true);
  });

  it('should detect version mismatch', () => {
    const currentVersion = '2.0.0';
    const ruleVersion = '1.0.0';

    const isCompatible = currentVersion === ruleVersion;
    expect(isCompatible).toBe(false);
  });
});

// ─── Round-trip Tests ───────────────────────────────────────────────────────

describe('Version Round-trip', () => {
  it('should preserve version through serialize-parse cycle', () => {
    const originalRule = buildRule({ name: 'Test', version: '1.5.0' });
    const yaml = serializeAutomodRule(originalRule);

    const parsed = parseAutomodRuleDraft(yaml);
    expect(parsed.name).toBe('Test');
    expect(parsed.version).toBe('1.5.0');
  });
});
